cart/urls.py
from django.urls import path
from .views import CartAdd, CartDelete, CartDetail

app_name = "cart"
urlpatterns = [
    path("add/<int:product_id>/", CartAdd.as_view(), name="cart_add"),
    path("remove/<int:product_id>/", CartDelete.as_view(), name="cart_remove"),
    path("", CartDetail.as_view(), name="cart_detail"),
]

coupons/urls.py
from django.urls import path
from .views import CouponApply

app_name = "coupons"

urlpatterns = [
    path("apply/", CouponApply.as_view(), name="apply"),
]

main/urls.py
from django.urls import path
from .views import ProductList, ProductDetail

app_name = "main"
urlpatterns = [
    path(
        "<slug:category_slug>/", ProductList.as_view(), name="product_list_by_category"
    ),
    path("<int:pk>/<slug:slug>/", ProductDetail.as_view(), name="product_detail"),
    path("", ProductList.as_view(), name="product_list"),
]

orders/urls.py
from django.urls import path
from .views import OrderCreate, AdminOrderDetail, AdminOrderPDF

app_name = "orders"

urlpatterns = [
    path(
        "admin/order/<int:order_id>/pdf/",
        AdminOrderPDF.as_view(),
        name="admin_order_pdf",
    ),
    path(
        "admin/order/<int:order_id>/'",
        AdminOrderDetail.as_view(),
        name="admin_order_detail",
    ),
    path("create/", OrderCreate.as_view(), name="order_create"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("main.urls", namespace="main")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label="Quantity"
    )
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import TemplateView
from main.models import Product
from main.recommender import Recommender
from coupons.forms import CouponApplyForm
from .cart import Cart
from .forms import CartAddProductForm


class CartAdd(View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(product, cd["quantity"], cd["update"])
        return redirect("cart:cart_detail")


class CartDelete(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect("cart:cart_detail")


class CartDetail(TemplateView):

    template_name = "cart/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["coupon_apply_form"] = CouponApplyForm()
        return context

    def get(self, request, *args, **kwargs):
        cart = Cart(request)
        for item in cart:
            item["update_quantity_form"] = CartAddProductForm(
                initial={"quantity": item["quantity"], "update": True}
            )
        cart.generete_cart()
        r = Recommender()
        cart_products = [item["product"] for item in cart]
        kwargs["recommended_products"] = r.suggest_products_for(
            cart_products, max_results=4
        )
        return super().get(self, request, *args, **kwargs)

cart/templates/cart/detail.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}Shopping cart{% endblock title %}

{% block content %}
    <h1>Shopping cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %}{{ product.image.url }}
                                    {% else %}{% static 'img/no_image.png' %}{% endif %}">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.update }}
                                {% csrf_token %}
                                <input type="submit" value="Update">
                            </form>
                        </td>
                        <td>
                            <a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
                        <td>$ {{ item.price }}</td>
                        <td>$ {{ item.total_price }}</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            {% if cart.coupon %}
                <tr class="subtotal">
                    <td>Subtotal</td>
                    <td colspan="4"></td>
                    <td class="num">
                        $ {{ cart.get_total_price|floatformat:"2" }}
                    </td>
                </tr>
                <tr>
                    <td>
                        "{{ cart.coupon.code }}" coupon ({{ cart.coupon.discount }}% off)
                    </td>
                    <td colspan="4"></td>
                    <td class="num neg">
                        - $ {{ cart.get_discount|floatformat:"2" }}
                    </td>
                </tr>
            {% endif %}
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">
                    $ {{ cart.get_total_price_after_discount|floatformat:"2" }}
                </td>
            </tr>
        </tbody>
    </table>

    {% if recommended_products %}
        <div class="recommendations cart">
            <h3>People who bought this also bought</h3>
            {% for p in recommended_products %}
                <div class="item">
                    <a href="{{ p.get_absolute_url }}">
                        <img src="{% if p.image %}{{ p.image.url }}{% else %}
                        {% static 'img/no_image.png' %}{% endif %}">
                    </a>
                    <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <p>Apply a coupon:</p>
    <form action="{% url 'coupons:apply' %}" method="POST">
        {{ coupon_apply_form }}
        {% csrf_token %}
        <input type="submit" value="Apply">
    </form>
    <p class="text-right">
        <a href="{% url 'main:product_list' %}" class="button light">Continue shopping</a>
        <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
    </p>
{% endblock content %}