cart/urls.py
from django.urls import path
from .views import CartAdd, CartDelete, CartDetail

app_name = "cart"
urlpatterns = [
    path("add/<int:product_id>/", CartAdd.as_view(), name="cart_add"),
    path("remove/<int:product_id>/", CartDelete.as_view(), name="cart_remove"),
    path("", CartDetail.as_view(), name="cart_detail"),
]

main/urls.py
from django.urls import path
from .views import ProductList, ProductDetail

app_name = "main"
urlpatterns = [
    path(
        "<slug:category_slug>/", ProductList.as_view(), name="product_list_by_category"
    ),
    path("<int:pk>/<slug:slug>/", ProductDetail.as_view(), name="product_detail"),
    path("", ProductList.as_view(), name="product_list"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("main.urls", namespace="main")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ["name"]
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("main:product_list_by_category", args=[self.slug])


class Product(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)
    category = models.ForeignKey(
        Category,
        related_name="product",
        on_delete=models.CASCADE,
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["id", "slug"]),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("main:product_detail", args=[self.id, self.slug])

main/views.py
from django.shortcuts import get_object_or_404
from django.views.generic.detail import DetailView
from django.views.generic.base import TemplateView
from cart.forms import CartAddProductForm
from .models import Category, Product
from .recommender import Recommender


class ProductList(TemplateView):
    template_name = "main/product/list.html"

    def get_queryset(self, **kwargs):
        products = Product.objects.filter(available=True)
        category = kwargs.get("category")
        if category:
            products = products.filter(category=category)
        return products

    def get_context_data(self, **kwargs):
        categories = Category.objects.all()
        return {
            "category": kwargs.get("category"),
            "categories": categories,
            "products": self.queryset,
        }

    def get(self, request, category_slug=None, *args, **kwargs):
        category = None
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)

        self.queryset = self.get_queryset(category=category)
        context = self.get_context_data(category=category)
        return self.render_to_response(context)


class ProductDetail(DetailView):
    template_name = "main/product/detail.html"
    queryset = Product.objects.filter(available=True)
    query_pk_and_slug = True
    context_object_name = "product"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        r = Recommender()
        context["cart_product_form"] = CartAddProductForm()
        context["recommended_products"] = r.suggest_products_for(
            [kwargs.get("object")], 4
        )
        return context

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <title>{% block title %}Shop{% endblock title %}</title>
</head>
<body>
    <div id="header">
        <a href="{% url 'main:product_list' %}" class="logo">Shop</a>
    </div>
    <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if total_items > 0 %}
                    <p>Your cart:</p>
                    <a href="{% url 'cart:cart_detail' %}">
                        {% with total=cart.get_total_price_after_discount items=total_items %}
                            {{ items }} item, ${{ total }}
                        {% endwith %}
                    </a>
                {% else %}
                    <p>Cart is empty</p>
                {% endif %}
            {% endwith %}
        </div>
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>